<a href="https://colab.research.google.com/github/shivamkumar359/3rd-SEM-CLASS-CODES/blob/main/IDB/W2/PRACTICAL_SESSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

teams_data = {
    'team_id': [1, 2, 3],
    'team_name': ['MI', 'CSK', 'RCB'],
    'city': ['Mumbai', 'Chennai', 'Bangalore'],
    'coach_name': ['Mark', 'Stephen', 'Andy']
}
teams = pd.DataFrame(teams_data)

players_data = {
    'player_id': [101, 102, 103, 104, 105, 106, 107, 108],
    'player_name': ['Rohit Sharma', 'Jasprit Bumrah', 'Hardik Pandya', 'MS Dhoni', 'Ravindra Jadeja', 'Virat Kohli', 'Mohammed Siraj', 'Glenn Maxwell'],
    'age': [36, 30, 30, 42, 35, 35, 29, 35],
    'role': ['batsman', 'bowler', 'all-rounder', 'wicket-keeper', 'all-rounder', 'batsman', 'bowler', 'all-rounder'],
    'team_id': [1, 1, 1, 2, 2, 3, 3, 3]
}


players = pd.DataFrame(players_data)

print("Team Table:")
display(teams)
print("\nPlayers Table:")
display(players)

Team Table:

   team_id team_name       city coach_name
0        1        MI     Mumbai       Mark
1        2       CSK    Chennai    Stephen
2        3       RCB  Bangalore       Andy

Players Table:

   player_id      player_name  age           role  team_id
0        101     Rohit Sharma   36        batsman        1
1        102   Jasprit Bumrah   30         bowler        1
2        103    Hardik Pandya   30    all-rounder        1
3        104         MS Dhoni   42  wicket-keeper        2
4        105  Ravindra Jadeja   35    all-rounder        2
5        106      Virat Kohli   35        batsman        3
6        107   Mohammed Siraj   29         bowler        3
7        108    Glenn Maxwell   35    all-rounder        3

In [ ]:
young_players = players[players['age'] < 31]
display(young_players)

   player_id     player_name  age         role  team_id
1        102  Jasprit Bumrah   30       bowler        1
2        103   Hardik Pandya   30  all-rounder        1
6        107  Mohammed Siraj   29       bowler        3

In [ ]:
young_bowlers = players[(players['role'] =='bowler') & (players['age'] < 31)]
display(young_bowlers)

   player_id     player_name  age    role  team_id
1        102  Jasprit Bumrah   30  bowler        1
6        107  Mohammed Siraj   29  bowler        3