<a href="https://colab.research.google.com/github/shivamkumar359/3rd-SEM-CLASS-CODES/blob/main/IDB/W2/PRACTICAL_SESSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd


teams_data = {
    'team_id': [1, 2, 3],
    'team_name': ['Mumbai Indians', 'Chennai Super Kings', 'Royal Challengers Bangalore'],
    'city': ['Mumbai', 'Chennai', 'Bangalore'],
    'coach_name': ['Mark Boucher', 'Stephen Fleming', 'Andy Flower']
}
teams = pd.DataFrame(teams_data)

players_data = {
    'player_id': [101, 102, 103, 104, 105, 106, 107, 108],
    'player_name': ['Rohit Sharma', 'Jasprit Bumrah', 'Hardik Pandya', 'MS Dhoni', 'Ravindra Jadeja', 'Virat Kohli', 'Mohammed Siraj', 'Glenn Maxwell'],
    'age': [36, 30, 30, 42, 35, 35, 29, 35],
    'role': ['batsman', 'bowler', 'all-rounder', 'wicket-keeper', 'all-rounder', 'batsman', 'bowler', 'all-rounder'],
    'team_id': [1, 1, 1, 2, 2, 3, 3, 3]
}
players = pd.DataFrame(players_data)

print("Teams Table:")
display(teams)
print("\nPlayers Table:")
display(players)

Teams Table:

   team_id                    team_name       city       coach_name
0        1               Mumbai Indians     Mumbai     Mark Boucher
1        2          Chennai Super Kings    Chennai  Stephen Fleming
2        3  Royal Challengers Bangalore  Bangalore      Andy Flower

Players Table:

   player_id      player_name  age           role  team_id
0        101     Rohit Sharma   36        batsman        1
1        102   Jasprit Bumrah   30         bowler        1
2        103    Hardik Pandya   30    all-rounder        1
3        104         MS Dhoni   42  wicket-keeper        2
4        105  Ravindra Jadeja   35    all-rounder        2
5        106      Virat Kohli   35        batsman        3
6        107   Mohammed Siraj   29         bowler        3
7        108    Glenn Maxwell   35    all-rounder        3

In [23]:
young_players = players[players['age'] < 32]
display(young_players)

   player_id     player_name  age         role  team_id
1        102  Jasprit Bumrah   30       bowler        1
2        103   Hardik Pandya   30  all-rounder        1
6        107  Mohammed Siraj   29       bowler        3

In [ ]:
young_bowlers = players[(players['role'] =='bowler') & (players['age'] < 31)]
display(young_bowlers)

   player_id     player_name  age    role  team_id
1        102  Jasprit Bumrah   30  bowler        1
6        107  Mohammed Siraj   29  bowler        3

In [24]:

all_rounders_info = players[players['role'] == 'all-rounder'][['player_name', 'age']]
display(all_rounders_info)

       player_name  age
2    Hardik Pandya   30
4  Ravindra Jadeja   35
7    Glenn Maxwell   35

## Part C — Set Operations
Union, Intersection, and Set Difference using the MI 2023 and 2024 squads.

In [ ]:
mi_2023 = pd.DataFrame(['player_name': ['Rohit sharma', ]])